// vue/src/components/messages/Messages.vue
<template>
    <div class="ui message">
        <div class="ui top left attached label">Messages</div>
        <h5>Messages</h5>
        <div class="ui list">
            <div class="item" v-for="(message, index) in messages" :key="index">{{message}}</div>
        </div>
        <div class="ui small button" @click="clear">Clear</div>
    </div>
</template>

<script>
import { mapState, mapActions } from "vuex";
export default {
    computed: {
        ...mapState(["messages"])
    },
    methods: {
        ...mapActions({
            clear: "clearMessages"
        })
    }
};
</script>

// angular/src/app/components/messages/messages.component.ts
import { Component } from '@angular/core';
import { MessageService } from 'src/app/services/message.service';

@Component({
    selector: 'app-messages',
    templateUrl: './messages.component.html',
    styleUrls: ['./messages.component.styl'],
})
export class MessagesComponent {
    constructor(private messageService: MessageService) {}

    public get messages() {
        return this.messageService.getMessages();
    }

    public clear() {
        this.messageService.clear();
    }
}

<div class="ui message">
    <div class="ui top left attached label">messages.component</div>
    <h5>Messages</h5>
    <div class="ui list">
        <div class="item" *ngFor="let message of messages">{{ message }}</div>
    </div>
    <div class="ui small button" (click)="clear()">Clear</div>
</div>
