// react/src/components/television/Television.js
import React, { Component } from 'react';
import { TelevisionService } from '../../services/TelevisionService';

const televisionService = new TelevisionService();

export class Television extends Component {
    state = {
        query: '',
        shows: [],
        loading: false
    };

    render() {
        return (
            <div>
                <div className='ui top left attached label'>Television</div>
                <div className='ui form'>
                    <div className='field'>
                        <div className={'ui icon input' + (this.state.loading ? ' loading' : '')}>
                            <input
                                type='text'
                                value={this.state.query}
                                name='query'
                                onChange={this.onChange}
                                onKeyDown={e => (e.key.toLowerCase() === 'enter' ? this.onSearch() : null)}
                                placeholder='Enter name or keywords. eg.: action, cars, music...'
                            />
                            <i className='circular search link icon' onClick={this.onSearch} />
                        </div>
                    </div>
                    <div className='ui divided items'>
                        {this.state.shows.map(show => (
                            <div className='item' key={show.id}>
                                {show.image ? <img className='image' src={show.image.medium} alt='' /> : ''}
                                <div className='content'>
                                    <div className='header'>{show.name}</div>
                                    <div className='description' dangerouslySetInnerHTML={{ __html: show.summary }} />
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        );
    }

    onSearch = async () => {
        const { query } = this.state;
        this.setState({
            loading: true
        });
        const result = await televisionService.getShows(query);
        this.setState({ shows: result.map(p => p.show), loading: false });
    };

    onChange = e => {
        this.setState({ [e.target.name]: e.target.value });
    };
}

// vue/src/components/television/Television.vue
<template>
    <div>
        <div class="ui top left attached label">Television</div>
        <div class="ui form">
            <div class="field">
                <div class="ui icon input" :class="{ loading: loading }">
                    <input
                        type="text"
                        placeholder="Enter name or keywords. eg.: action, cars, music..."
                        v-model="query"
                        @keydown.enter="onSearch"
                    >
                    <i class="circular search link icon" @click="onSearch"></i>
                </div>
            </div>
            <div class="ui divided items">
                <div class="item" v-for="show in shows" :key="show.id">
                    <img :src="show.image.medium" v-if="show.image" alt class="image">
                    <div class="content">
                        <div class="header">{{ show.name }}</div>
                        <div class="description" v-html="show.summary"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { TelevisionService } from "@/services/TelevisionService";

const televisionService = new TelevisionService();

export default {
    data() {
        return {
            query: "",
            shows: [],
            loading: false
        };
    },

    methods: {
        async onSearch() {
            this.loading = true;
            const response = await televisionService.getShows(this.query);
            this.shows = response.map(p => p.show);
            this.loading = false;
        }
    }
};
</script>
