// angular/src/app/components/television/television.component.ts
import { Component } from '@angular/core';
import { TelevisionService } from 'src/app/services/television-service.service';

@Component({
    selector: 'app-television',
    templateUrl: './television.component.html',
    styleUrls: ['./television.component.styl'],
})
export class TelevisionComponent {
    public query = '';
    public shows = [];
    public loading = false;

    constructor(private televisionService: TelevisionService) {}

    public onSearch() {
        this.loading = true;
        this.televisionService.getShows(this.query).subscribe(value => {
            this.loading = false;
            this.shows = value.map((p: { show: any }) => p.show);
        });
    }
}

<div class="ui top left attached label">television.component</div>
<div class="ui form">
    <div class="field">
        <div class="ui icon input" [class.loading]="loading">
            <input
                type="text"
                placeholder="Enter name or keywords. eg.: action, cars, music..."
                [(ngModel)]="query"
                (keydown.enter)="onSearch()"
            />
            <i class="circular search link icon" (click)="onSearch()"></i>
        </div>
    </div>
    <div class="ui divided items">
        <div class="item" *ngFor="let show of shows">
            <img
                [src]="show.image.medium"
                *ngIf="show.image"
                alt=""
                class="image"
            />
            <div class="content">
                <div class="header">{{ show.name }}</div>
                <div class="description" [innerHTML]="show.summary"></div>
            </div>
        </div>
    </div>
</div>

// vue/src/components/television/Television.vue
<template>
    <div>
        <div class="ui top left attached label">Television</div>
        <div class="ui form">
            <div class="field">
                <div class="ui icon input" :class="{ loading: loading }">
                    <input
                        type="text"
                        placeholder="Enter name or keywords. eg.: action, cars, music..."
                        v-model="query"
                        @keydown.enter="onSearch"
                    >
                    <i class="circular search link icon" @click="onSearch"></i>
                </div>
            </div>
            <div class="ui divided items">
                <div class="item" v-for="show in shows" :key="show.id">
                    <img :src="show.image.medium" v-if="show.image" alt class="image">
                    <div class="content">
                        <div class="header">{{ show.name }}</div>
                        <div class="description" v-html="show.summary"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { TelevisionService } from "@/services/TelevisionService";

const televisionService = new TelevisionService();

export default {
    data() {
        return {
            query: "",
            shows: [],
            loading: false
        };
    },

    methods: {
        async onSearch() {
            this.loading = true;
            const response = await televisionService.getShows(this.query);
            this.shows = response.map(p => p.show);
            this.loading = false;
        }
    }
};
</script>
