// angular/src/app/layouts/main-layout/main-layout.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-main-layout',
    templateUrl: './main-layout.component.html',
    styleUrls: ['./main-layout.component.styl'],
})
export class MainLayoutComponent {
    constructor() {}
}

<div class="ui fluid container">
    <div class="ui top attached label">
        main-layout.component
    </div>
    <h1 class="title">Angular App</h1>
    <div class="ui menu">
        <a class="item" routerLink="/heroes">Heroes</a>
        <a class="item" routerLink="/tv">Television</a>
        <a class="item" routerLink="/about">About</a>
    </div>

    <section class="ui grid">
        <div class="ten wide column">
            <div class="ui segment">
                <router-outlet></router-outlet>
            </div>
        </div>
        <div class="six wide column">
            <app-messages></app-messages>
        </div>
    </section>
</div>

// react/src/layouts/MainLayout.js
import React, { Component } from 'react';
import { Route, Link, Redirect } from 'react-router-dom';
import { Heroes } from '../components/heroes/Heroes';
import { About } from '../components/about/About';
import { Messages } from '../components/messages/Messages';
import './MainLayout.css';
import { Television } from '../components/television/Television';

export class MainLayout extends Component {
    render() {
        return (
            <div className='ui fluid container'>
                <div className='ui top attached label'>MainLayout</div>
                <h1 className='title'>React App</h1>
                <div className='ui menu'>
                    <Link className='item' to='/heroes'>
                        Heroes
                    </Link>
                    <Link className='item' to='/tv'>
                        Television
                    </Link>
                    <Link className='item' to='/about'>
                        About
                    </Link>
                </div>

                <section className='ui grid'>
                    <div className='ten wide column'>
                        <div className='ui segment'>
                            <Route path='/' exact render={() => <Redirect to='/heroes' />} />
                            <Route path='/heroes' component={Heroes} />
                            <Route path='/tv' component={Television} />
                            <Route path='/about' component={About} />
                        </div>
                    </div>
                    <div className='six wide column'>
                        <Messages />
                    </div>
                </section>
            </div>
        );
    }
}
