// vue/src/layouts/MainLayout.vue
<template>
    <div class="ui fluid container">
        <div class="ui top attached label">MainLayout</div>
        <h1 class="title">Vue App</h1>
        <div class="ui menu">
            <router-link class="item" to="/heroes">Heroes</router-link>
            <router-link class="item" to="/tv">Television</router-link>
            <router-link class="item" to="/about">About</router-link>
        </div>

        <section class="ui grid">
            <div class="ten wide column">
                <div class="ui segment">
                    <router-view></router-view>
                </div>
            </div>
            <div class="six wide column">
                <messages></messages>
            </div>
        </section>
    </div>
</template>

<script>
import Messages from "@/components/messages/Messages";
export default {
    components: {
        Messages
    }
};
</script>

<style lang="stylus" scoped>
.ui.container
    position relative
    border 1px solid #ddd
    padding 20px

h1
    padding-top 20px
</style>

// react/src/layouts/MainLayout.js
import React, { Component } from 'react';
import { Route, Link, Redirect } from 'react-router-dom';
import { Heroes } from '../components/heroes/Heroes';
import { About } from '../components/about/About';
import { Messages } from '../components/messages/Messages';
import './MainLayout.css';
import { Television } from '../components/television/Television';

export class MainLayout extends Component {
    render() {
        return (
            <div className='ui fluid container'>
                <div className='ui top attached label'>MainLayout</div>
                <h1 className='title'>React App</h1>
                <div className='ui menu'>
                    <Link className='item' to='/heroes'>
                        Heroes
                    </Link>
                    <Link className='item' to='/tv'>
                        Television
                    </Link>
                    <Link className='item' to='/about'>
                        About
                    </Link>
                </div>

                <section className='ui grid'>
                    <div className='ten wide column'>
                        <div className='ui segment'>
                            <Route path='/' exact render={() => <Redirect to='/heroes' />} />
                            <Route path='/heroes' component={Heroes} />
                            <Route path='/tv' component={Television} />
                            <Route path='/about' component={About} />
                        </div>
                    </div>
                    <div className='six wide column'>
                        <Messages />
                    </div>
                </section>
            </div>
        );
    }
}
