// vue/src/components/heroes/HeroesDetail.vue
<template>
    <div class="ui card form" v-if="hero" :class="{ loading: loading }">
        <div class="ui top left attached label">HeroesDetail</div>
        <div class="content">
            <div class="header">Hero Details</div>
            <div class="description">
                <table class="ui definition table">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td>{{ hero.id }}</td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>
                                <div class="field">
                                    <input
                                        type="text"
                                        v-model="hero.name"
                                        placeholder="Enter hero's name..."
                                    >
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="ui basic buttons">
                    <div class="ui icon button" @click="onSave(hero)">
                        <i class="check icon"></i>
                        Save
                    </div>
                    <div class="ui icon button" @click="onDelete(hero)">
                        <i class="trash icon"></i>
                        Delete
                    </div>
                    <div class="ui icon button" @click="onCancel(hero)">
                        <i class="ban icon"></i>
                        Cancel
                    </div>
                </div>
                <div class="ui custom message">
                    <span class="header">{{ hero.name }}</span>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { HeroService } from "@/services/HeroService";

const heroService = new HeroService();

export default {
    props: {
        hero: {
            required: true,
            validation: value => {
                return "id" in value && "name" in value;
            }
        }
    },
    data() {
        return {
            loading: false
        };
    },
    methods: {
        onCancel() {
            this.$emit("canceled");
        },
        async onDelete() {
            this.loading = true;
            await heroService.delete(this.hero);
            this.loading = false;
            this.$emit("deleted");
        },
        async onSave() {
            this.loading = true;
            const hero = await heroService.save(this.hero);
            this.loading = false;
            this.$emit("saved", hero);
        }
    }
};
</script>


<style lang="stylus" scoped>
.ui.card.form
    width auto !important

.ui.custom.message .header
    font-size 36px
    padding 1em
</style>

// react/src/components/heroes/HeroesDetail.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { HeroService } from '../../services/HeroService';

import './HeroesDetail.css';

const heroService = new HeroService();

export class HeroesDetail extends Component {
    constructor(props) {
        super(props);
        this.state = {
            hero: props.hero,
            loading: false
        };
    }
    componentWillReceiveProps(props) {
        this.setState((state, _props) => ({
            hero: props.hero
        }));
    }
    onSave = async () => {
        this.setState((state, props) => ({ loading: true }));
        const hero = await heroService.save(this.state.hero);
        this.setState((state, props) => ({ loading: false, hero }));
        this.props.saved(this.state.hero);
    };
    onDelete = async () => {
        this.setState((state, props) => ({ loading: true }));
        await heroService.delete(this.state.hero);
        this.setState((state, props) => ({ loading: false }));
        this.props.deleted();
    };
    onCancel = () => {
        this.props.canceled();
    };
    onNameChange = e => {
        const name = e.target.value;
        this.setState((state, props) => ({
            hero: { ...state.hero, name }
        }));
    };
    render() {
        return (
            <div className={'ui card form' + (this.state.loading ? ' loading' : '')}>
                <div className='ui top left attached label'>HeroesDetail</div>
                <div className='content'>
                    <div className='header'>Hero Details</div>
                    <div className='description'>
                        <table className='ui definition table'>
                            <tbody>
                                <tr>
                                    <td>ID</td>
                                    <td>{this.state.hero.id}</td>
                                </tr>
                                <tr>
                                    <td>Name</td>
                                    <td>
                                        <div className='field'>
                                            <input
                                                type='text'
                                                placeholder="Enter hero's name..."
                                                value={this.state.hero.name}
                                                onChange={this.onNameChange}
                                            />
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div className='ui basic buttons'>
                            <div className='ui icon button' onClick={this.onSave}>
                                <i className='check icon' />
                                Save
                            </div>
                            <div className='ui icon button' onClick={this.onDelete}>
                                <i className='trash icon' />
                                Delete
                            </div>
                            <div className='ui icon button' onClick={this.onCancel}>
                                <i className='ban icon' />
                                Cancel
                            </div>
                        </div>
                        <div className='ui custom message'>
                            <span className='header'>{this.state.hero.name}</span>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

HeroesDetail.propTypes = {
    hero: PropTypes.shape({
        id: PropTypes.string,
        name: PropTypes.string
    }).isRequired,
    saved: PropTypes.func,
    deleted: PropTypes.func,
    canceled: PropTypes.func
};
