// angular/src/app/components/heroes-list/heroes-list.component.ts
import {
    Component,
    OnInit,
    Output,
    EventEmitter,
    OnDestroy,
} from '@angular/core';
import { Hero } from 'src/app/models/heroes/Hero';
import { HeroService } from 'src/app/services/hero.service';
import { Subscription } from 'rxjs';

@Component({
    selector: 'app-heroes-list',
    templateUrl: './heroes-list.component.html',
    styleUrls: ['./heroes-list.component.styl'],
})
export class HeroesListComponent implements OnInit, OnDestroy {
    public selectedHero: Hero;
    public loading = false;
    public heroes: Hero[];
    public heroAction: Subscription;

    @Output() public selected: EventEmitter<Hero> = new EventEmitter<Hero>();

    constructor(private heroService: HeroService) {}

    public ngOnInit() {
        this.heroAction = this.heroService.action.subscribe(msg => {
            if (msg) {
                this.loadHeroes();
                console.log('Load by heroAction');
            }
        });
        this.loadHeroes();
        console.log('Load by ngOnInit');
    }

    public ngOnDestroy() {
        console.log('Unsubscribe heroAction');
        this.heroAction.unsubscribe();
    }

    public async loadHeroes() {
        this.loading = true;
        const response = await this.heroService.getHeroes();
        response.subscribe(heroes => {
            this.heroes = heroes;
            this.loading = false;
        });
    }

    public onSelect(hero: Hero) {
        this.selectedHero = hero;
        this.selected.emit(hero);
    }
}

<div class="ui segment">
    <div class="ui top left attached label">heroes-list.component</div>
    <h5>Heroes Team</h5>
    <div class="scroller">
        <div class="ui inverted dimmer" [class.active]="loading">
            <div class="ui loader"></div>
        </div>
        <div class="ui divided selection list">
            <div
                class="item"
                *ngFor="let hero of heroes"
                [class.active]="selectedHero && selectedHero.id === hero.id"
                (click)="onSelect(hero)"
            >
                {{ hero.name }}<br />
                <small>{{ hero.id }}</small>
            </div>
        </div>
    </div>
</div>

// vue/src/components/heroes/HeroesList.vue
<template>
    <div class="ui segment">
        <div class="ui top left attached label">HeroesList</div>
        <h5>Heroes Team</h5>
        <div class="scroller">
            <div class="ui inverted dimmer" :class="{ 'active': loading }">
                <div class="ui loader"></div>
            </div>
            <div class="ui divided selection list">
                <div
                    class="item"
                    v-for="hero in heroes"
                    :key="hero.id"
                    :class="{'active': selectedHero && selectedHero.id === hero.id}"
                    @click="onSelect(hero)"
                >
                    {{hero.name}}
                    <br>
                    <small>{{hero.id}}</small>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { HeroService } from "@/services/HeroService";

const heroService = new HeroService();

export default {
    data() {
        return {
            heroes: [],
            loading: false,
            selectedHero: null
        };
    },
    methods: {
        async loadHeroes() {
            this.loading = true;
            this.heroes = await heroService.getHeroes();
            this.loading = false;
        },
        onSelect(hero) {
            this.selectedHero = hero;
            this.$emit("selected", hero);
        }
    },
    mounted() {
        this.loadHeroes();
    }
};
</script>


<style lang="stylus" scoped>
.scroller
    height 280px
    overflow-y scroll
</style>
