// react/src/components/heroes/Heroes.js
import React, { Component } from 'react';
import { HeroesDetail } from './HeroesDetail';
import { HeroesList } from './HeroesList';

export class Heroes extends Component {
    state = {
        selectedHero: null
    };

    onAdd = () => {
        this.setState((state, props) => ({
            selectedHero: { id: null, name: '' }
        }));
    };

    onSelected = hero => {
        this.setState((state, props) => ({
            selectedHero: hero
        }));
    };

    onSaved = hero => {
        console.log('Hero saved!', hero);
        this.setState((state, props) => ({
            selectedHero: { ...hero }
        }));
        this.refs.heroesList.loadHeroes();
    };

    onDeleted = () => {
        console.log('Hero deleted!');
        this.setState((state, props) => ({
            selectedHero: null
        }));
        this.refs.heroesList.loadHeroes();
    };

    onCanceled = () => {
        console.log('Changes canceled!');
        this.setState((state, props) => ({
            selectedHero: null
        }));
    };

    render() {
        return (
            <div className='ui grid'>
                <div className='ui top left attached label'>Heroes</div>
                <div className='row'>
                    <div className='ten wide column'>
                        {this.state.selectedHero ? (
                            <HeroesDetail
                                hero={this.state.selectedHero}
                                saved={this.onSaved}
                                deleted={this.onDeleted}
                                canceled={this.onCanceled}
                            />
                        ) : (
                            <div className='ui massive circular icon green button' onClick={this.onAdd}>
                                <i className='plus icon' />
                            </div>
                        )}
                    </div>
                    <div className='six wide column'>
                        <HeroesList selected={this.onSelected} ref='heroesList' />
                    </div>
                </div>
                <div className='row'>
                    <div className='column' />
                </div>
            </div>
        );
    }
}

// vue/src/components/heroes/Heroes.vue
<template>
    <div class="ui grid">
        <div class="ui top left attached label">Heroes</div>
        <div class="row">
            <div class="ten wide column">
                <div
                    class="ui massive circular icon green button"
                    v-if="!selectedHero"
                    @click="onAdd"
                >
                    <i class="plus icon"></i>
                </div>
                <heroes-detail
                    :hero="selectedHero"
                    @saved="onSaved"
                    @deleted="onDeleted"
                    @canceled="onCanceled"
                    v-else
                ></heroes-detail>
            </div>
            <div class="six wide column">
                <heroes-list @selected="onSelected" ref="heroesList"></heroes-list>
            </div>
        </div>
    </div>
</template>

<script>
import HeroesDetail from "./HeroesDetail";
import HeroesList from "./HeroesList";

export default {
    components: {
        HeroesList,
        HeroesDetail
    },
    data() {
        return {
            selectedHero: null
        };
    },
    methods: {
        onSelected(hero) {
            this.selectedHero = { ...hero };
        },
        onAdd() {
            this.selectedHero = { id: null, name: "" };
        },
        onSaved(hero) {
            console.log("Hero saved!", hero);
            this.selectedHero = { ...hero };
            this.$refs.heroesList.loadHeroes();
        },
        onDeleted() {
            console.log("Hero deleted!");
            this.selectedHero = null;
            this.$refs.heroesList.loadHeroes();
        },
        onCanceled() {
            console.log("Changes canceled!");
            this.selectedHero = null;
        }
    }
};
</script>
