// angular/src/app/components/about/about.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-about',
    templateUrl: './about.component.html',
    styleUrls: ['./about.component.styl'],
})

export class AboutComponent {}

<div>
    <div class="ui top left attached label">about.component</div>
    <p>Hi there! <strong>Angular</strong> here.</p>
</div>

// react/src/components/about/About.js
import React, { Component } from 'react';
import styles from './About.css';

export class About extends Component {
    render() {
        return (
            <div>
                <div className='ui top left attached label'>About</div>
                <p className={styles.p}>
                    Hi there! <strong className={styles.strong}>React</strong> here.
                </p>
            </div>
        );
    }
}
